import type { Language } from './types'

/**
 * All seeker-facing copy lives here — nothing hardcoded in components.
 * `meta` is the exception: it's the demo-controls panel, an internal tool for
 * the three founders, not part of the product surface, so it stays in English
 * regardless of the language toggle.
 */

export const strings = {
  el: {
    app: {
      name: 'ShareIt',
    },
    common: {
      notSpecified: 'Δεν έχει οριστεί',
      showEverything: 'εμφάνιση όλων',
      backToResults: 'Πίσω στα αποτελέσματα',
    },
    entry: {
      title: 'Βρες δωμάτιο',
      areaLabel: 'Περιοχή',
      budgetLabel: 'Προϋπολογισμός (μηνιαίως)',
      budgetPlaceholder: 'π.χ. 350',
      billsIncludedToggle: 'Να περιλαμβάνει λογαριασμούς',
      minStayLabel: 'Ελάχιστη διαμονή (μήνες)',
      maxStayLabel: 'Μέγιστη διαμονή (μήνες)',
      freeTextLabel: 'Κάτι άλλο;',
      freeTextPlaceholder: 'π.χ. κοντά στο μετρό, φοιτητικό',
      submit: 'Αναζήτηση',
      haveARoomLink: 'Έχεις δωμάτιο; Καταχώρισέ το',
    },
    freshness: {
      today: 'σήμερα',
      yesterday: 'χθες',
      daysAgo: (n: number) => `πριν από ${n} μέρες`,
      renewedToday: 'ανανεώθηκε σήμερα',
      renewedYesterday: 'ανανεώθηκε χθες',
      renewedDaysAgo: (n: number) => `ανανεώθηκε πριν από ${n} μέρες`,
      expiringNote: 'Μπορεί να μην είναι πια διαθέσιμο',
      expiredCount: (n: number) => `${n} αγγελίες έληξαν πρόσφατα`,
    },
    results: {
      // areaLabel arrives pre-formed per language — "στου Ζωγράφου" (el) or "Zografou" (en).
      countInArea: (count: number, areaLabel: string) => `${count} δωμάτια ${areaLabel}`,
      // Used until the Entry screen supplies a real area filter (build order §9, step 5).
      countTotal: (count: number) => `${count} διαθέσιμα δωμάτια`,
      thinSupplyNote: 'Δεν είναι πολλά ακόμα.',
      zeroResults: 'Καμία διαθέσιμη αγγελία αυτή τη στιγμή.',
      sort: {
        label: 'Ταξινόμηση',
        recency: 'Πιο πρόσφατα',
        price: 'Τιμή',
        duration: 'Διάρκεια',
      },
      card: {
        billsIncluded: 'με λογαριασμούς',
        billsExcluded: 'χωρίς λογαριασμούς',
        availableFrom: (date: string) => `Διαθέσιμο από ${date}`,
        durationOpenEnded: (min: string) => `από ${min}`,
        durationRange: (min: string, max: string) => `${min}–${max}`,
        months: (n: number) => (n === 1 ? '1 μήνα' : `${n} μήνες`),
        noPhotos: 'Χωρίς φωτογραφίες',
        photoCount: (n: number) => (n === 1 ? '1 φωτογραφία' : `${n} φωτογραφίες`),
        seededBadge: 'Από την ομάδα',
        matchBadge: (pct: number) => `${pct}% ταίριασμα`,
        matchBadgeSubtext: 'Φάση 2 — δεν έχει χτιστεί, δεν έχει επικυρωθεί',
      },
    },
    preferencePass: {
      sheetHeadline: (count: number, areaLabel: string) =>
        `${count} δωμάτια ${areaLabel}. Τρεις ερωτήσεις και θα δεις αυτά που αξίζει να ανοίξεις.`,
      // No area filter applied yet (Entry may not have set one) — same pitch, no place name.
      sheetHeadlineGeneric: (count: number) =>
        `${count} διαθέσιμα δωμάτια. Τρεις ερωτήσεις και θα δεις αυτά που αξίζει να ανοίξεις.`,
      questions: {
        billsIncluded: 'Το ενοίκιο να περιλαμβάνει λογαριασμούς;',
        maxFlatmates: 'Θα έμενες με πάνω από δύο άτομα;',
        earliestMove: 'Πότε είναι το νωρίτερο που θα μετακόμιζες;',
      },
      yes: 'Ναι',
      no: 'Όχι',
      earliestOptions: {
        asap: 'Άμεσα',
        thisMonth: 'Μέσα στον μήνα',
        flexible: 'Είμαι ευέλικτος/η',
      },
      skip: 'Παράλειψη',
      escapeHatch: 'Απλά θέλω να δω',
      matchHeader: (matching: number, total: number) =>
        `${matching} από ${total} δωμάτια ταιριάζουν με ό,τι μας είπες`,
      showMatches: 'εμφάνιση όσων ταιριάζουν',
      inlinePromptExample: 'Αυτό το διαμέρισμα έχει κήπο. Σε νοιάζει αυτό;',
    },
    detail: {
      availableFromLabel: 'Διαθέσιμο από',
      durationLabel: 'Διάρκεια',
      typeLabel: 'Τύπος δωματίου',
      roomType: { private: 'Ιδιωτικό δωμάτιο', shared: 'Κοινόχρηστο δωμάτιο' },
      flatmatesLabel: 'Συγκάτοικοι',
      maxStayIndefinite: 'Χωρίς όριο διαμονής',
      attributeLabels: { pets: 'Κατοικίδια', smoking: 'Κάπνισμα', couples: 'Ζευγάρια', students: 'Φοιτητές' },
      attributeYes: 'Επιτρέπεται',
      attributeNo: 'Δεν επιτρέπεται',
      askTheLister: 'Ρώτα τον/την',
      descriptionLabel: 'Περιγραφή',
      expiresIn: (n: number) => `Λήγει σε ${n === 1 ? '1 μέρα' : `${n} μέρες`} εκτός αν ανανεωθεί.`,
      expiredAgo: (n: number) => `Έληξε πριν από ${n === 1 ? '1 μέρα' : `${n} μέρες`}.`,
      revealCta: 'Δες στοιχεία επικοινωνίας',
    },
    wall: {
      title: 'Σύνδεση για να δεις τα στοιχεία',
      reason: 'Μόνο για να δεις τα στοιχεία επικοινωνίας. Δεν δημοσιεύουμε τίποτα.',
      googleSignIn: 'Σύνδεση με Google',
    },
    revealed: {
      title: 'Στοιχεία επικοινωνίας',
      openWhatsapp: 'Άνοιγμα WhatsApp',
      call: 'Κλήση',
      email: 'Αποστολή email',
      replyHookQuestion: 'Πήρες απάντηση;',
      replyYes: 'Ναι',
      replyNo: 'Όχι',
      replyNotYet: 'Δεν ρώτησα ακόμα',
      replyThanks: 'Ευχαριστούμε!',
    },
    post: {
      title: 'Καταχώρισε ένα δωμάτιο',
      areaLabel: 'Περιοχή',
      rentLabel: 'Ενοίκιο (μηνιαίως)',
      rentPlaceholder: 'π.χ. 320',
      billsIncludedToggle: 'Περιλαμβάνει λογαριασμούς',
      availableFromLabel: 'Διαθέσιμο από',
      minStayLabel: 'Ελάχιστη διαμονή (μήνες)',
      maxStayLabel: 'Μέγιστη διαμονή (μήνες, προαιρετικό)',
      descriptionLabel: 'Περιγραφή',
      descriptionPlaceholder: 'Πες μας για το δωμάτιο, το σπίτι, τους συγκατοίκους...',
      submit: 'Δημοσίευση',
    },
    live: {
      title: 'Η αγγελία σου είναι live',
      expiresOn: (date: string) => `Λήγει σε 14 μέρες, στις ${date}.`,
      protectionFraming:
        'Έτσι δεν σε παίρνουν τηλέφωνο για δωμάτιο που έχει ήδη φύγει. Δύο μέρες πριν λήξει θα σε ρωτήσουμε αν θες να την ανανεώσεις — ένα tap, τίποτα παραπάνω.',
      previewLabel: 'Έτσι τη βλέπει όποιος ψάχνει δωμάτιο:',
      identityBannerText: 'Σύνδεση για να μπορείς να αλλάξεις ή να κατεβάσεις την αγγελία σου.',
      identitySignIn: 'Σύνδεση με Google',
      identityDismiss: 'Αργότερα',
    },
    renewal: {
      question: 'Είναι ακόμα διαθέσιμο το δωμάτιο;',
      renew: 'Ανανέωση',
      gone: 'Έφυγε',
      askTomorrow: 'Ρώτα με αύριο',
      renewedConfirmation: (date: string) => `Ανανεώθηκε. Λήγει ${date}.`,
      goneConfirmation: 'Η αγγελία αρχειοθετήθηκε.',
    },
  },
  en: {
    app: {
      name: 'ShareIt',
    },
    common: {
      notSpecified: 'Not specified',
      showEverything: 'show everything',
      backToResults: 'Back to results',
    },
    entry: {
      title: 'Find a room',
      areaLabel: 'Area',
      budgetLabel: 'Budget (per month)',
      budgetPlaceholder: 'e.g. 350',
      billsIncludedToggle: 'Must include bills',
      minStayLabel: 'Minimum stay (months)',
      maxStayLabel: 'Maximum stay (months)',
      freeTextLabel: 'Anything else?',
      freeTextPlaceholder: 'e.g. near the metro, student-friendly',
      submit: 'Search',
      haveARoomLink: 'Have a room? Post it',
    },
    freshness: {
      today: 'today',
      yesterday: 'yesterday',
      daysAgo: (n: number) => `${n} days ago`,
      renewedToday: 'renewed today',
      renewedYesterday: 'renewed yesterday',
      renewedDaysAgo: (n: number) => `renewed ${n} days ago`,
      expiringNote: 'May no longer be available',
      expiredCount: (n: number) => `${n} listings expired recently`,
    },
    results: {
      countInArea: (count: number, areaLabel: string) => `${count} rooms in ${areaLabel}`,
      countTotal: (count: number) => `${count} rooms available`,
      thinSupplyNote: 'That is not many yet.',
      zeroResults: 'No listings available right now.',
      sort: {
        label: 'Sort',
        recency: 'Most recent',
        price: 'Price',
        duration: 'Duration',
      },
      card: {
        billsIncluded: 'bills included',
        billsExcluded: 'bills excluded',
        availableFrom: (date: string) => `Available from ${date}`,
        durationOpenEnded: (min: string) => `from ${min}`,
        durationRange: (min: string, max: string) => `${min}–${max}`,
        months: (n: number) => (n === 1 ? '1 month' : `${n} months`),
        noPhotos: 'No photos',
        photoCount: (n: number) => (n === 1 ? '1 photo' : `${n} photos`),
        seededBadge: 'Posted by the team',
        matchBadge: (pct: number) => `${pct}% match`,
        matchBadgeSubtext: 'Phase 2 — not built, not validated',
      },
    },
    preferencePass: {
      sheetHeadline: (count: number, areaLabel: string) =>
        `${count} rooms in ${areaLabel}. Three questions and you'll see the ones worth opening.`,
      sheetHeadlineGeneric: (count: number) =>
        `${count} rooms available. Three questions and you'll see the ones worth opening.`,
      questions: {
        billsIncluded: 'Bills included in the rent?',
        maxFlatmates: 'Would you share with more than two people?',
        earliestMove: 'Earliest you’d move?',
      },
      yes: 'Yes',
      no: 'No',
      earliestOptions: {
        asap: 'As soon as possible',
        thisMonth: 'Within the month',
        flexible: "I'm flexible",
      },
      skip: 'Skip',
      escapeHatch: 'Just let me look',
      matchHeader: (matching: number, total: number) =>
        `${matching} of ${total} rooms match what you've told us`,
      showMatches: 'show matches',
      inlinePromptExample: 'This flat has a garden. Does that matter to you?',
    },
    detail: {
      availableFromLabel: 'Available from',
      durationLabel: 'Duration',
      typeLabel: 'Room type',
      roomType: { private: 'Private room', shared: 'Shared room' },
      flatmatesLabel: 'Flatmates',
      maxStayIndefinite: 'No maximum stay',
      attributeLabels: { pets: 'Pets', smoking: 'Smoking', couples: 'Couples', students: 'Students' },
      attributeYes: 'Allowed',
      attributeNo: 'Not allowed',
      askTheLister: 'Ask the lister',
      descriptionLabel: 'Description',
      expiresIn: (n: number) => `Expires in ${n} ${n === 1 ? 'day' : 'days'} unless renewed.`,
      expiredAgo: (n: number) => `Expired ${n} ${n === 1 ? 'day' : 'days'} ago.`,
      revealCta: 'See contact details',
    },
    wall: {
      title: 'Sign in to see contact details',
      reason: 'Only to see contact details. We don’t publish anything.',
      googleSignIn: 'Sign in with Google',
    },
    revealed: {
      title: 'Contact details',
      openWhatsapp: 'Open WhatsApp',
      call: 'Call',
      email: 'Send email',
      replyHookQuestion: 'Did you get a reply?',
      replyYes: 'Yes',
      replyNo: 'No',
      replyNotYet: "Haven't asked yet",
      replyThanks: 'Thanks!',
    },
    post: {
      title: 'Post a room',
      areaLabel: 'Area',
      rentLabel: 'Rent (per month)',
      rentPlaceholder: 'e.g. 320',
      billsIncludedToggle: 'Includes bills',
      availableFromLabel: 'Available from',
      minStayLabel: 'Minimum stay (months)',
      maxStayLabel: 'Maximum stay (months, optional)',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Tell us about the room, the flat, the flatmates...',
      submit: 'Publish',
    },
    live: {
      title: 'Your listing is live',
      expiresOn: (date: string) => `It expires in 14 days, on ${date}.`,
      protectionFraming:
        "That way nobody rings you about a room that's already gone. Two days before it expires we'll ask if you want to renew it — one tap, nothing more.",
      previewLabel: 'This is how a seeker sees it:',
      identityBannerText: 'Sign in so you can edit or take down your listing later.',
      identitySignIn: 'Sign in with Google',
      identityDismiss: 'Later',
    },
    renewal: {
      question: 'Is this room still available?',
      renew: 'Renew',
      gone: "It's gone",
      askTomorrow: 'Ask me tomorrow',
      renewedConfirmation: (date: string) => `Renewed. Expires ${date}.`,
      goneConfirmation: 'The listing has been archived.',
    },
  },
} satisfies Record<Language, unknown>

export const meta = {
  demoPanel: {
    title: 'Demo controls',
    hint: 'Ctrl/⌘ + Shift + D to toggle',
    supply: { label: 'Supply', cold: 'Thin', full: 'Liquid' },
    freshness: { label: 'Freshness', on: 'Expiry on', off: 'Expiry off' },
    profile: { label: 'Profile', empty: 'Empty', partial: 'Partial', complete: 'Complete' },
    matching: { label: 'Matching', off: 'Off', preview: 'Preview' },
    language: { label: 'Language', el: 'Greek', en: 'English' },
    clock: { label: 'Clock', today: 'Today', day12: 'Day 12', day15: 'Day 15' },
  },
}
